/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is the REST API used by Salicorne/PKITool
 *
 * API version: 0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package server

import (
	"encoding/json"
	"net/http"
	"pkitool/storage"

	"github.com/gorilla/mux"
)

func GetFullPKI(w http.ResponseWriter, r *http.Request) {
	pkiName, ok := mux.Vars(r)["pki-name"]
	if !ok {
		response(w, http.StatusBadRequest, "pki-name not provided") // should not happen according to router
	}

	var storer storage.Storer = &storage.FilesystemStorer{BasePath: pkiName}

	details, err := storer.GetFullPki()
	if err != nil {
		response(w, http.StatusInternalServerError, err.Error())
	}

	detailsBytes, err := json.Marshal(details)
	if err != nil {
		response(w, http.StatusInternalServerError, err.Error())
	}

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	w.Write(detailsBytes)
}

func ListPKIs(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func CreatePKI(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
