/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is the REST API used by Salicorne/PKITool
 *
 * API version: 0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package server

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"GetCert",
		strings.ToUpper("Get"),
		"/cert/{pki-name}/{serial-number}",
		GetCert,
	},

	Route{
		"GetKey",
		strings.ToUpper("Get"),
		"/key/{pki-name}/{serial-number}",
		GetKey,
	},

	Route{
		"GetP12",
		strings.ToUpper("Get"),
		"/p12/{pki-name}/{serial-number}",
		GetP12,
	},

	Route{
		"CreateCert",
		strings.ToUpper("Post"),
		"/pki/{pki-name}/{serial-number}/cert",
		CreateCert,
	},

	Route{
		"CreatePKI",
		strings.ToUpper("Post"),
		"/pki",
		CreatePKI,
	},

	Route{
		"CreateSubCa",
		strings.ToUpper("Post"),
		"/pki/{pki-name}/{serial-number}/ca",
		CreateSubCa,
	},

	Route{
		"GetFullPKI",
		strings.ToUpper("Get"),
		"/pki/{pki-name}",
		GetFullPKI,
	},

	Route{
		"ListPKIs",
		strings.ToUpper("Get"),
		"/pki",
		ListPKIs,
	},
}
