/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is the REST API used by Salicorne/PKITool
 *
 * API version: 0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type PkiDetails struct {

	SerialNumber string `json:"serialNumber"`

	Ca bool `json:"ca"`

	CertUrl string `json:"certUrl,omitempty"`

	KeyUrl string `json:"keyUrl,omitempty"`

	P12Url string `json:"p12Url,omitempty"`

	SubCaRequestUrl string `json:"subCaRequestUrl,omitempty"`

	CertRequestUrl string `json:"certRequestUrl,omitempty"`

	Children []PkiDetails `json:"children,omitempty"`
}
